# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[cache]
  # Evita la caché de archivos estáticos
  public = true
  # Tiempo de vida de los archivos (en segundos)
  ttl = 600
